import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link, useLocation } from "react-router-dom";
import { Moon, Sun, LogOut, Menu } from "lucide-react";
import { useTheme } from "@/hooks";
import { useState } from "react";
export const Layout = ({ children, user, onLogout, }) => {
    const { theme, toggleTheme, mounted } = useTheme();
    const location = useLocation();
    const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
    if (!mounted) {
        return (_jsx("div", { className: "min-h-screen bg-black flex items-center justify-center", children: _jsx("div", { className: "animate-pulse text-white", children: "Loading..." }) }));
    }
    const navLinks = [
        { path: "/dashboard", label: "Dashboard", icon: "📊" },
        { path: "/explore", label: "Explore", icon: "🔍" },
        { path: "/matches", label: "Matches", icon: "🎯" },
        { path: "/generate", label: "Generate", icon: "⚙️" },
    ];
    const isActive = (path) => location.pathname === path;
    return (_jsxs("div", { className: "min-h-screen flex flex-col bg-transparent text-white", children: [_jsx("nav", { className: "fixed top-0 w-full z-50 border-b border-white/10 bg-black/40 backdrop-blur-xl", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex items-center justify-between h-16", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("button", { onClick: () => setMobileMenuOpen(!mobileMenuOpen), className: "p-2 rounded-lg hover:bg-white/10 transition-colors", "aria-label": "Toggle menu", children: _jsx(Menu, { size: 20 }) }), user && (_jsxs("div", { className: "flex items-center gap-3 px-3 py-1 rounded-lg bg-white/5 border border-white/10", children: [_jsx("div", { className: "w-8 h-8 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center", children: _jsx("span", { className: "text-xs font-bold text-white", children: user.username.charAt(0).toUpperCase() }) }), _jsx("span", { className: "text-sm font-medium text-gray-300", children: user.username })] }))] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("button", { onClick: toggleTheme, className: "p-2 rounded-lg hover:bg-white/10 transition-colors cursor-pointer", "aria-label": "Toggle theme", title: `Switch to ${theme === "dark" ? "light" : "dark"} mode`, children: theme === "dark" ? (_jsx(Sun, { size: 20, className: "text-yellow-400" })) : (_jsx(Moon, { size: 20, className: "text-gray-300" })) }), user && onLogout && (_jsx("button", { onClick: onLogout, className: "p-2 rounded-lg hover:bg-red-500/10 hover:text-red-400 text-gray-400 transition-colors", "aria-label": "Logout", title: "Logout", children: _jsx(LogOut, { size: 20 }) }))] })] }) }) }), mobileMenuOpen && (_jsxs(_Fragment, { children: [_jsx("div", { className: "fixed inset-0 bg-black/50 backdrop-blur-sm z-40 transition-opacity", onClick: () => setMobileMenuOpen(false) }), _jsx("div", { className: "fixed left-0 top-16 h-screen w-64 bg-black/95 backdrop-blur-xl border-r border-white/10 z-40 animate-in slide-in-from-left-96 duration-300", children: _jsx("div", { className: "flex flex-col gap-2 p-4", children: navLinks.map((link) => (_jsxs(Link, { to: link.path, className: `px-6 py-4 rounded-lg text-base font-medium transition-all flex items-center gap-3 ${isActive(link.path)
                                    ? "bg-blue-600 text-white shadow-lg shadow-blue-600/30"
                                    : "text-gray-300 hover:bg-white/10"}`, onClick: () => setMobileMenuOpen(false), children: [_jsx("span", { className: "text-2xl", children: link.icon }), _jsx("span", { children: link.label })] }, link.path))) }) })] })), _jsx("main", { className: "flex-1 pt-16 pb-12", children: children }), _jsx("footer", { className: "border-t border-white/10 bg-black/50 backdrop-blur-sm py-8", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-8 mb-8", children: [_jsxs("div", { className: "space-y-3", children: [_jsx("h3", { className: "font-semibold text-white", children: "HackQuest AI" }), _jsx("p", { className: "text-sm text-gray-400", children: "Win your next hackathon with AI-powered insights, profile analysis, and winning strategies." })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("h3", { className: "font-semibold text-white", children: "Quick Links" }), _jsxs("ul", { className: "space-y-2 text-sm", children: [_jsx("li", { children: _jsx("a", { href: "#", className: "text-gray-400 hover:text-blue-400 transition-colors", children: "Documentation" }) }), _jsx("li", { children: _jsx("a", { href: "#", className: "text-gray-400 hover:text-blue-400 transition-colors", children: "API Docs" }) }), _jsx("li", { children: _jsx("a", { href: "#", className: "text-gray-400 hover:text-blue-400 transition-colors", children: "GitHub" }) })] })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("h3", { className: "font-semibold text-white", children: "Support" }), _jsxs("ul", { className: "space-y-2 text-sm", children: [_jsx("li", { children: _jsx("a", { href: "#", className: "text-gray-400 hover:text-blue-400 transition-colors", children: "Contact Us" }) }), _jsx("li", { children: _jsx("a", { href: "#", className: "text-gray-400 hover:text-blue-400 transition-colors", children: "Feedback" }) }), _jsx("li", { children: _jsx("a", { href: "#", className: "text-gray-400 hover:text-blue-400 transition-colors", children: "Status" }) })] })] })] }), _jsxs("div", { className: "border-t border-white/10 pt-6 flex flex-col sm:flex-row items-center justify-between text-sm text-gray-400", children: [_jsx("p", { children: "\u00A9 2025 HackQuest AI. All rights reserved." }), _jsxs("div", { className: "flex gap-6 mt-4 sm:mt-0", children: [_jsx("a", { href: "#", className: "hover:text-white transition-colors", children: "Privacy" }), _jsx("a", { href: "#", className: "hover:text-white transition-colors", children: "Terms" }), _jsx("a", { href: "#", className: "hover:text-white transition-colors", children: "Cookies" })] })] })] }) })] }));
};
Layout.displayName = "Layout";
